import { temporaryMedia } from './siteContent'

export const projectPlaceholders = [
  {
    title: 'Specialtillverkning',
    slug: 'specialtillverkning',
    category: 'Exempelbild',
    description:
      'Här kommer Lucas egna bilder på specialtillverkade produkter att visas. Bilden är tillfällig i designförslaget.',
    image: temporaryMedia.weldingWorkshop,
    seoTitle: 'Specialtillverkning i Götene, Västra Götaland – Projektexempel',
    seoDescription: 'Projektexempel för måttanpassade metalldetaljer: uppmätning, kapning, svetsning och passning. Skarp Smed & Mek utgår från Götene i Västra Götalands län.',
    heading: 'Måttanpassade metalldetaljer i Götene',
    intro: 'När en standardprodukt inte passar kan en specialtillverkad metalldetalj vara lösningen. Skarp Smed & Mek utgår från Götene och hjälper till med specialtillverkning för uppdrag i Västra Götalands län.',
    workTitle: 'Från mått och skiss till ett anpassat stålfäste',
    workDescription: 'Ett exempel på den här typen av uppdrag är ett stålfäste som behöver anpassas till en befintlig konstruktion. Då behöver infästningar, tillgängligt utrymme och användning gås igenom innan materialet kapas och delarna sammanfogas. Arbetsbeskrivningen nedan visar ett möjligt upplägg, inte ett dokumenterat kundjobb.',
    steps: [
      'Gå igenom skiss, mått, hålbild och hur fästet ska användas.',
      'Välja material och dimensioner utifrån konstruktionens krav.',
      'Kapa, borra och passa in de ingående metalldelarna.',
      'Svetsa samman delarna och bearbeta kanter och svetsytor vid behov.',
      'Kontrollera mått och passning före överlämning eller montering.',
    ],
    result: 'Målet är en detalj som passar sin avsedda plats och funktion. I ett färdigt projekt beskriver vi vilka mått, material och infästningar som användes samt visar resultatet med bilder.',
    serviceSlug: 'specialtillverkning-metall',
    serviceLabel: 'Specialtillverkning i metall',
  },
  {
    title: 'Svets & smide',
    slug: 'svets-smide',
    category: 'Exempelbild',
    description:
      'Projektgalleriet är förberett för riktiga jobb med kort beskrivning av vad som tillverkades eller reparerades.',
    image: temporaryMedia.weldingCloseup,
    seoTitle: 'Svets & smide i Götene, Västra Götaland – Projektexempel',
    seoDescription: 'Se ett exempel på upplägg för svetsreparation av en ståldetalj. Skarp Smed & Mek arbetar med svets och smide från Götene i Västra Götalands län.',
    heading: 'Svets och smide med utgångspunkt i Götene',
    intro: 'En skadad ståldetalj kan behöva repareras, förstärkas eller ersättas. Skarp Smed & Mek arbetar med svets och smide från Götene och tar uppdrag i Västra Götalands län, både i verkstad och på plats när arbetet lämpar sig för det.',
    workTitle: 'Bedömning och svetsreparation av en ståldetalj',
    workDescription: 'Ett tänkbart uppdrag är en ståldetalj med en skadad svetsfog eller ett slitet parti. Arbetet börjar med att undersöka skadan och bedöma om reparation är lämplig eller om delen behöver bytas ut. Följande moment är ett exempel på arbetsgången, inte en redovisning av ett utfört projekt.',
    steps: [
      'Undersöka skadan, materialet och detaljens funktion.',
      'Avgöra om detaljen ska repareras eller ersättas.',
      'Rengöra arbetsytan och förbereda fog och passning.',
      'Utföra svetsningen med en metod som passar materialet och arbetet.',
      'Kontrollera fog, form och passning samt efterbearbeta vid behov.',
    ],
    result: 'Arbetets omfattning styrs av detaljens skick och användning. För ett genomfört jobb kompletteras sidan med skadebild, vald åtgärd och bilder som visar skillnaden före och efter arbetet.',
    serviceSlug: 'smed-svets',
    serviceLabel: 'Svets och smide',
  },
  {
    title: 'Maskin & mek',
    slug: 'maskin-mek',
    category: 'Exempelbild',
    description:
      'Den här platsen ersätts med dokumentation från ett verkligt maskin- eller reparationsjobb innan lansering.',
    image: temporaryMedia.machineRepair,
    seoTitle: 'Maskinreparation i Götene, Västra Götaland – Projektexempel',
    seoDescription: 'Projektexempel för reparation av maskinfästen och mekaniska delar: bedömning, demontering, åtgärd och funktionskontroll. Utgångspunkt Götene.',
    heading: 'Maskinreparation och mek i Västra Götaland',
    intro: 'Slitna fästen och skadade mekaniska delar kan hindra en maskin från att fungera som den ska. Skarp Smed & Mek utgår från Götene och hjälper till med maskinreparation och mekaniska arbeten i Västra Götalands län.',
    workTitle: 'Reparation eller anpassning av ett maskinfäste',
    workDescription: 'Ett exempel är ett maskinfäste som har slitits eller skadats och behöver återställas eller ersättas. Först behöver maskinens användning och orsaken till skadan undersökas. Upplägget nedan beskriver möjliga arbetsmoment och ska ersättas med uppgifterna från ett verkligt uppdrag.',
    steps: [
      'Gå igenom maskintyp, symptom och bilder på den skadade delen.',
      'Undersöka infästningar, slitage och behov av demontering.',
      'Bedöma om delen kan repareras eller behöver nytillverkas.',
      'Utföra överenskommen mekanisk bearbetning, anpassning eller svetsning.',
      'Återmontera och kontrollera passning och funktion enligt uppdragets omfattning.',
    ],
    result: 'Målet är en fungerande lösning anpassad till maskinen och användningen. I projektets slutliga beskrivning anges vilken maskin eller del arbetet gällde, vad som åtgärdades och hur resultatet kontrollerades.',
    serviceSlug: 'maskinreparation-mek',
    serviceLabel: 'Maskinreparation och mek',
  },
]
